# Checkov Configuration for Terraform Security Scanning
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Framework to scan
framework:
  - terraform

# Output formats
output:
  - cli
  - junitxml

# Soft fail mode - không fail build nếu có security issues (để học tập)
# Set thành false trong production để enforce security policies
soft-fail: true

# Compact mode for cleaner output
compact: true

# Download external Terraform modules
download-external-modules: true

# Skip specific checks (uncomment để bỏ qua các checks cụ thể)
# skip-check:
#   - CKV_AWS_79   # Ensure Instance Metadata Service Version 1 is not enabled
#   - CKV_AWS_8    # Ensure all data stored in the Launch configuration EBS is securely encrypted
#   - CKV_AWS_46   # Ensure no hard-coded secrets exist in EC2 user data
#   - CKV_AWS_126  # Ensure that detailed monitoring is enabled for EC2 instances
#   - CKV_AWS_135  # Ensure that EC2 is EBS optimized
#   - CKV_AWS_88   # EC2 instance should not have public IP

# Checks to skip for specific files
# skip-path:
#   - modules/vpc/main.tf

# Custom policies directory (nếu có)
# external-checks-dir:
#   - ./custom-policies
