project:
  name: cfn-infrastructure-project
  owner: devops-lab-student
  regions:
    - us-east-1
  package_lambda: false
  
tests:
  # Test 1: Deploy main infrastructure stack
  full-deployment:
    template: Lab01/cloudformation/main.yaml
    parameters:
      ProjectName: taskcat-test
      UserIP: 0.0.0.0/0
      KeyPairName: override-key
      TemplatesBucketURL: $[taskcat_autobucket]
      VpcCidr: 10.0.0.0/16
      PublicSubnetCidr: 10.0.1.0/24
      PrivateSubnetCidr: 10.0.2.0/24
    regions:
      - us-east-1
