version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.11"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat
      - cfn-lint --version
      - taskcat --version
  pre_build:
    commands:
      - pwd
      - find cloudformation -name "*.yaml" -o -name "*.yml"
  build:
    commands:
      - |
        cfn-lint cloudformation/**/*.yaml
        CFN_LINT_EXIT=$?
        if [ $CFN_LINT_EXIT -eq 2 ]; then
          exit 1
        fi
      - taskcat test run --skip-upload-to-s3
  post_build:
    commands:
      - |
        if [ -d taskcat_outputs ]; then
          ls -la taskcat_outputs/
        fi
artifacts:
  files:
    - "**/*"
  secondary-artifacts:
    TaskcatReports:
      files:
        - "taskcat_outputs/**/*"
      name: taskcat-test-results
reports:
  TaskcatTestReport:
    files:
      - "taskcat_outputs/**/taskcat_report.json"
    file-format: "JUNITXML"
cache:
  paths:
    - "/root/.cache/pip/**/*"
