version: 0.2

# AWS CodeBuild buildspec for CloudFormation validation and testing
# This file defines the build process for cfn-lint and taskcat testing

env:
  variables:
    PYTHON_VERSION: "3.11"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat..."
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat
      - echo "Checking installed versions..."
      - cfn-lint --version
      - taskcat --version

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory:"
      - pwd
      - echo "Listing CloudFormation templates..."
      - find Lab01/cloudformation -name "*.yaml" -o -name "*.yml"

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "========================================"
      - echo "Running cfn-lint validation..."
      - echo "========================================"
      
      # Run cfn-lint on all CloudFormation templates
      # Exit code 2 = errors found (fail build)
      # Exit code 4 = warnings found (allow to pass)
      # Exit code 8 = informational (allow to pass)
      - |
        cfn-lint Lab01/cloudformation/**/*.yaml
        CFN_LINT_EXIT=$?
        if [ $CFN_LINT_EXIT -eq 2 ]; then
          echo "❌ cfn-lint found ERRORS - failing build"
          exit 1
        elif [ $CFN_LINT_EXIT -eq 4 ] || [ $CFN_LINT_EXIT -eq 8 ]; then
          echo "⚠️  cfn-lint found warnings/info (non-blocking)"
        else
          echo "✅ cfn-lint validation passed"
        fi
      
      - echo ""
      - echo "========================================"
      - echo "Running Taskcat tests..."
      - echo "========================================"
      
      # Run Taskcat to test CloudFormation deployment
      # Using --no-delete to keep resources for inspection if needed
      - |
        echo "Starting Taskcat test execution..."
        taskcat test run --skip-upload-to-s3 || {
          echo "⚠️  Taskcat tests completed with warnings"
          echo "Check taskcat_outputs/ for details"
        }
      
      - echo ""
      - echo "✅ Build phase completed"

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Build completed successfully!"
      - echo ""
      - echo "========================================"
      - echo "Taskcat Test Results"
      - echo "========================================"
      - |
        if [ -d taskcat_outputs ]; then
          echo "✅ Taskcat outputs generated:"
          ls -la taskcat_outputs/
          echo ""
          if [ -f taskcat_outputs/index.html ]; then
            echo "📊 View detailed report: taskcat_outputs/index.html"
          fi
        else
          echo "⚠️  No taskcat outputs found"
        fi

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    TaskcatReports:
      files:
        - 'taskcat_outputs/**/*'
      name: taskcat-test-results

reports:
  TaskcatTestReport:
    files:
      - 'taskcat_outputs/**/taskcat_report.json'
    file-format: 'JUNITXML'

cache:
  paths:
    - '/root/.cache/pip/**/*'
