AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Security Groups cho EC2 Instances trong VPC đã tạo'

#INPUT
Parameters:
  UserIP:
    Type: String
    Description: Địa chỉ IP của người dùng để cấu hình SSH Access
  KeyPairName:
    Type: String
    Description: Tên của Key Pair để gán cho EC2 Instances


Resources:
#Security Groups
  #Public SG
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group cho Public EC2 Instances
      VpcId: !ImportValue nt548-vpc-stack-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref UserIP
      Tags:
        - Key: Name
          Value: cf-public-sg
  #Private SG
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group cho Private EC2 Instances
      VpcId: !ImportValue nt548-vpc-stack-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup
      Tags:
        - Key: Name
          Value: cf-private-sg
  #Public EC2
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue nt548-vpc-stack-PublicSubnetId
          GroupSet:
            - !Ref PublicSecurityGroup
      Tags:
        - Key: Name
          Value: cf-public-ec2
  #Private EC2
  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          SubnetId: !ImportValue nt548-vpc-stack-PrivateSubnetId
          GroupSet:
            - !Ref PrivateSecurityGroup
      Tags:
        - Key: Name
          Value: cf-private-ec2

Outputs:
  PublicEC2IP:
    Description: IP Public của máy chủ Public
    Value: !GetAtt PublicEC2Instance.PublicIp
  PrivateEC2IP:
    Description: IP Private của máy chủ Private
    Value: !GetAtt PrivateEC2Instance.PrivateIp