AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Module - Creates Public and Private EC2 instances

Parameters:
  ProjectName:
    Type: String
    Default: cf-project
    Description: Project name for resource tagging

  PublicSubnetId:
    Type: String
    Description: Public Subnet ID for public EC2 instance

  PrivateSubnetId:
    Type: String
    Description: Private Subnet ID for private EC2 instance

  PublicSGId:
    Type: String
    Description: Public Security Group ID

  PrivateSGId:
    Type: String
    Description: Private Security Group ID

  KeyName:
    Type: String
    Description: Key Pair name for SSH access

Resources:
  # 1. PUBLIC EC2 INSTANCE
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnetId
          GroupSet:
            - !Ref PublicSGId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-public-ec2

  # 2. PRIVATE EC2 INSTANCE
  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      # Get latest Amazon Linux 2023 AMI dynamically
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}"
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          SubnetId: !Ref PrivateSubnetId
          GroupSet:
            - !Ref PrivateSGId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-private-ec2

Outputs:
  PublicEC2IP:
    Description: Public EC2 instance public IP
    Value: !GetAtt PublicEC2Instance.PublicIp

  PrivateEC2IP:
    Description: Private EC2 instance private IP
    Value: !GetAtt PrivateEC2Instance.PrivateIp
