version: 0.2

# AWS CodeBuild buildspec for CloudFormation validation and testing
# This file defines the build process for cfn-lint and taskcat testing

env:
  variables:
    PYTHON_VERSION: "3.11"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat..."
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat
      - echo "Checking installed versions..."
      - cfn-lint --version
      - taskcat --version

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory:"
      - pwd
      - echo "Listing CloudFormation templates..."
      - find Lab01/cloudformation -name "*.yaml" -o -name "*.yml"

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "========================================"
      - echo "Running cfn-lint validation..."
      - echo "========================================"
      
      # Run cfn-lint on all CloudFormation templates
      - |
        if cfn-lint Lab01/cloudformation/**/*.yaml; then
          echo "✅ cfn-lint validation PASSED"
        else
          echo "❌ cfn-lint validation FAILED"
          exit 1
        fi
      
      - echo ""
      - echo "========================================"
      - echo "Running Taskcat testing..."
      - echo "========================================"
      
      # Run taskcat test (only if .taskcat.yml exists)
      - |
        if [ -f .taskcat.yml ]; then
          taskcat test run --no-delete
          TASKCAT_EXIT_CODE=$?
          
          if [ $TASKCAT_EXIT_CODE -eq 0 ]; then
            echo "✅ Taskcat testing PASSED"
          else
            echo "❌ Taskcat testing FAILED with exit code: $TASKCAT_EXIT_CODE"
            exit 1
          fi
        else
          echo "⚠️  .taskcat.yml not found, skipping Taskcat tests"
        fi

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Build completed successfully!"
      - |
        if [ -d taskcat_outputs ]; then
          echo "Taskcat outputs generated:"
          ls -la taskcat_outputs/
        fi

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    TaskcatReports:
      files:
        - 'taskcat_outputs/**/*'
      name: taskcat-test-results

reports:
  TaskcatTestReport:
    files:
      - 'taskcat_outputs/**/taskcat_report.json'
    file-format: 'JUNITXML'

cache:
  paths:
    - '/root/.cache/pip/**/*'
