apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tuongndb1609/frontend:22
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        env:
        - name: DB_HOST
          value: "postgres-service" 
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend         
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80
  type: ClusterIP      