apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
  labels:
    app: note-service
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
      - name: note-service
        image: tuongndb1609/note-service:67
        imagePullPolicy: Always
        ports:
        - containerPort: 8082 
        env:
        - name: DB_HOST
          value: "postgres-service" 
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "note_service"
        - name: DB_USERNAME
          value: "note_service"
        - name: DB_PASSWORD
          value: "Aa123456"
---
apiVersion: v1
kind: Service
metadata:
  name: note-service  
  labels:
    app: note-service
spec:
  selector:
    app: note-service          
  ports:
    - protocol: TCP
      port: 8082          
      targetPort: 8082    
  type: ClusterIP         