apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: tuongndb1609/noteonline-postgres:67
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "Aa123456"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service  
  labels:
    app: postgres
spec:
  selector:
    app: postgres         
  ports:
    - protocol: TCP
      port: 5432          
      targetPort: 5432    
  type: ClusterIP         