apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  revisionHistoryLimit: 2
  replicas: 1 
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: tuongndb1609/user-service:67
        imagePullPolicy: Always
        ports:
        - containerPort: 8081 
        env:
        - name: DB_HOST
          value: "postgres-service" 
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "user_service"
        - name: DB_USERNAME
          value: "user_service"
        - name: DB_PASSWORD
          value: "Aa123456"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service  
  labels:
    app: user-service
spec:
  selector:
    app: user-service         
  ports:
    - protocol: TCP
      port: 8081          
      targetPort: 8081    
  type: ClusterIP         