AWSTemplateFormatVersion: "2010-09-09"
Description: Main Stack - Orchestrates VPC, Security Groups, and EC2 modules using Nested Stacks

Parameters:
  ProjectName:
    Type: String
    Default: cf-project
    Description: Project name for resource tagging

  UserIP:
    Type: String
    Description: Your IP address for SSH access (e.g., 1.2.3.4/32)

  KeyPairName:
    Type: String
    Description: Key Pair name for SSH access to EC2 instances

  TemplatesBucketURL:
    Type: String
    Description: S3 bucket URL where nested stack templates are stored (e.g., https://my-bucket.s3.amazonaws.com)
    Default: ""

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VPC

  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for Public Subnet

  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for Private Subnet

Resources:
  # MODULE 1: VPC
  VPCModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/modules/vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-vpc-module

  # MODULE 2: SECURITY GROUPS
  SecurityGroupsModule:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCModule
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/modules/security-groups.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCModule.Outputs.VPCId
        UserIP: !Ref UserIP
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-sg-module

  # MODULE 3: EC2
  EC2Module:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCModule
      - SecurityGroupsModule
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/modules/ec2.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        PublicSubnetId: !GetAtt VPCModule.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCModule.Outputs.PrivateSubnetId
        PublicSGId: !GetAtt SecurityGroupsModule.Outputs.PublicSGId
        PrivateSGId: !GetAtt SecurityGroupsModule.Outputs.PrivateSGId
        KeyName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ec2-module

Outputs:
  VPCId:
    Description: VPC ID from VPC module
    Value: !GetAtt VPCModule.Outputs.VPCId

  PublicSubnetId:
    Description: Public Subnet ID from VPC module
    Value: !GetAtt VPCModule.Outputs.PublicSubnetId

  PrivateSubnetId:
    Description: Private Subnet ID from VPC module
    Value: !GetAtt VPCModule.Outputs.PrivateSubnetId

  PublicSGId:
    Description: Public Security Group ID from Security Groups module
    Value: !GetAtt SecurityGroupsModule.Outputs.PublicSGId

  PrivateSGId:
    Description: Private Security Group ID from Security Groups module
    Value: !GetAtt SecurityGroupsModule.Outputs.PrivateSGId

  PublicEC2IP:
    Description: Public EC2 instance public IP from EC2 module
    Value: !GetAtt EC2Module.Outputs.PublicEC2IP

  PrivateEC2IP:
    Description: Private EC2 instance private IP from EC2 module
    Value: !GetAtt EC2Module.Outputs.PrivateEC2IP
